PREFIX cut: <https://example.org/cognitive-urban-twin#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?resource
WHERE {
  cut:DecisionContext_Heatwave_01 cut:hasAvailableFlexibility ?resource .
}
